-- Tabla "especies"
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Dicrostonyx groenlandicus', 77921.32, 174, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Phoenicopterus ruber', 145515.2, 135, 'Media', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Crocuta crocuta', 9067.71, 57, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Chloephaga melanoptera', 87979.88, 72, 'Baja', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Ramphastos tucanus', 130417.93, 22, 'Baja', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Pelecanus conspicillatus', 91716.46, 170, 'Baja', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Phoeniconaias minor', 93237.13, 199, 'Media', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Canis lupus baileyi', 69483.6, 180, 'Media', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Bettongia penicillata', 124277.24, 68, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Bassariscus astutus', 134598.74, 196, 'Media', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Cynictis penicillata', 72378.35, 160, 'Media', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Larus sp.', 23616.11, 191, 'Alta', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Macropus robustus', 12593.91, 69, 'Media', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Tockus erythrorhyncus', 103010.88, 81, 'Alta', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Aonyx cinerea', 50687.06, 70, 'Media', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Gopherus agassizii', 331.2, 14, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Tamandua tetradactyla', 34532.92, 156, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Macropus agilis', 139741.81, 128, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Canis lupus lycaon', 24954.36, 167, 'Baja', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Semnopithecus entellus', 73932.6, 52, 'Baja', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Eudyptula minor', 106879.0, 166, 'Alta', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Branta canadensis', 108999.17, 113, 'Alta', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Limosa haemastica', 91031.49, 94, 'Media', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Macaca mulatta', 28320.51, 73, 'Baja', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Coendou prehensilis', 101185.06, 54, 'Baja', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Genetta genetta', 79763.83, 108, 'Media', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Equus hemionus', 74553.44, 36, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Melursus ursinus', 147006.2, 157, 'Media', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Dacelo novaeguineae', 27503.13, 1, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Hymenolaimus malacorhynchus', 110959.5, 141, 'Alta', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Helogale undulata', 29196.24, 58, 'Alta', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Agkistrodon piscivorus', 9362.47, 103, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Perameles nasuta', 103404.25, 145, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Otocyon megalotis', 73510.14, 184, 'Alta', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Francolinus coqui', 123115.95, 14, 'Alta', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Zalophus californicus', 128990.22, 34, 'Media', 'herbívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Lamprotornis chalybaeus', 13627.27, 86, 'Baja', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Lepus arcticus', 116006.41, 13, 'Baja', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Theropithecus gelada', 115889.27, 59, 'Baja', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Smithopsis crassicaudata', 4663.65, 6, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Axis axis', 14955.15, 98, 'Alta', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Trachyphonus vaillantii', 13455.49, 17, 'Alta', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Centrocercus urophasianus', 135941.5, 84, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Sus scrofa', 61253.52, 15, 'Baja', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Semnopithecus entellus', 127367.34, 24, 'Media', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Anas punctata', 95681.66, 64, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Connochaetus taurinus', 128140.76, 197, 'Alta', 'carnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Plegadis falcinellus', 62775.42, 155, 'Alta', 'piscívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Eurocephalus anguitimens', 121180.43, 53, 'Baja', 'omnívoro');
insert into especies (nombre, peso_maximo, esperanza_de_vida, peligrosidad, dieta) values ('Phoca vitulina', 14959.07, 165, 'Alta', 'omnívoro');

-- Tabla "habitats"
insert into habitats (nombre, tipo, tamanio) values ('Russia', 'Montaña', 900.2);
insert into habitats (nombre, tipo, tamanio) values ('China', 'Selva', 990.12);
insert into habitats (nombre, tipo, tamanio) values ('Ukraine', 'Sabana', 125.28);
insert into habitats (nombre, tipo, tamanio) values ('Serbia', 'Desierto', 913.96);
insert into habitats (nombre, tipo, tamanio) values ('Venezuela', 'Selva', 474.87);
insert into habitats (nombre, tipo, tamanio) values ('China', 'Sabana', 550.44);
insert into habitats (nombre, tipo, tamanio) values ('Indonesia', 'Desierto', 536.0);
insert into habitats (nombre, tipo, tamanio) values ('Mongolia', 'Acuático', 335.52);
insert into habitats (nombre, tipo, tamanio) values ('Tunisia', 'Sabana', 33.49);
insert into habitats (nombre, tipo, tamanio) values ('China', 'Desierto', 708.16);
insert into habitats (nombre, tipo, tamanio) values ('Kosovo', 'Selva', 22.55);
insert into habitats (nombre, tipo, tamanio) values ('Finland', 'Sabana', 733.89);
insert into habitats (nombre, tipo, tamanio) values ('China', 'Montaña', 495.74);
insert into habitats (nombre, tipo, tamanio) values ('Ethiopia', 'Selva', 75.79);
insert into habitats (nombre, tipo, tamanio) values ('Indonesia', 'Montaña', 392.42);
insert into habitats (nombre, tipo, tamanio) values ('Brazil', 'Montaña', 835.47);
insert into habitats (nombre, tipo, tamanio) values ('Qatar', 'Sabana', 2.1);
insert into habitats (nombre, tipo, tamanio) values ('Czech Republic', 'Selva', 991.86);
insert into habitats (nombre, tipo, tamanio) values ('China', 'Selva', 243.81);
insert into habitats (nombre, tipo, tamanio) values ('Kazakhstan', 'Sabana', 638.79);
insert into habitats (nombre, tipo, tamanio) values ('China', 'Montaña', 609.93);
insert into habitats (nombre, tipo, tamanio) values ('Brazil', 'Selva', 429.57);
insert into habitats (nombre, tipo, tamanio) values ('Saudi Arabia', 'Desierto', 513.08);
insert into habitats (nombre, tipo, tamanio) values ('Indonesia', 'Selva', 274.3);
insert into habitats (nombre, tipo, tamanio) values ('Indonesia', 'Montaña', 39.55);

-- Tabla "animales"
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Chaddie', 'H', 70, 32, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Arlina', 'M', 72, 22, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Brynne', 'M', 77, 39, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Velma', 'H', 60, 13, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rogers', 'M', 73, 49, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ebeneser', 'H', 87, 27, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Shellysheldon', 'H', 29, 7, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Wolf', 'H', 94, 13, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Wylma', 'M', 8, 27, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Desirae', 'H', 80, 4, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sim', 'H', 31, 1, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Vicky', 'M', 24, 2, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Adele', 'H', 53, 3, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Lindi', 'M', 2, 35, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Milo', 'M', 23, 50, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Banky', 'H', 33, 19, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ronalda', 'H', 18, 3, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sollie', 'M', 1, 5, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Yvonne', 'H', 83, 34, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Libby', 'H', 44, 15, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Laure', 'M', 31, 41, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jessy', 'H', 8, 50, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Minna', 'H', 56, 44, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bella', 'H', 87, 45, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Lona', 'M', 82, 8, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hersch', 'M', 94, 34, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Harlie', 'H', 59, 40, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Clifford', 'M', 73, 37, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Terese', 'H', 92, 39, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Mace', 'M', 24, 27, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Starla', 'M', 56, 14, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Murdoch', 'M', 92, 41, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Lauryn', 'H', 79, 15, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Merilee', 'H', 40, 4, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Dennison', 'H', 42, 32, 18);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ignacio', 'H', 35, 39, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Krissy', 'M', 95, 8, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bev', 'H', 30, 11, 6);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Melodee', 'M', 49, 49, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Thane', 'M', 75, 1, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hollie', 'M', 62, 29, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Donnamarie', 'M', 71, 8, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Joseito', 'H', 47, 10, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Keslie', 'H', 86, 3, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Camile', 'M', 42, 40, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Culley', 'H', 35, 1, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Julee', 'H', 26, 49, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Helaine', 'M', 92, 25, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Edin', 'H', 76, 47, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sidonia', 'H', 47, 26, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Wileen', 'H', 98, 43, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Grazia', 'M', 38, 7, 6);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Catherina', 'H', 40, 38, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Dick', 'M', 25, 21, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Pepillo', 'H', 20, 26, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Mimi', 'H', 30, 20, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Emanuele', 'M', 25, 33, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Maurizio', 'M', 47, 40, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Virgie', 'M', 89, 40, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gale', 'H', 6, 27, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bret', 'H', 58, 17, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Kellia', 'H', 10, 14, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Kurtis', 'H', 4, 19, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Leif', 'M', 7, 45, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Robin', 'M', 44, 14, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Emlyn', 'M', 52, 48, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Corilla', 'H', 25, 6, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jody', 'H', 2, 34, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Constance', 'M', 48, 1, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Austine', 'H', 25, 37, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Loni', 'H', 39, 33, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Cyril', 'M', 11, 27, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jeniffer', 'M', 22, 6, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gerry', 'M', 71, 36, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Archer', 'H', 85, 19, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Saundra', 'H', 49, 43, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jerrilee', 'M', 68, 45, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hewie', 'H', 72, 40, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Berne', 'H', 87, 15, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ernie', 'H', 94, 40, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Thornie', 'H', 73, 49, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Danielle', 'M', 96, 34, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Lynnet', 'H', 21, 48, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Joana', 'M', 35, 44, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Catlaina', 'M', 7, 10, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sioux', 'M', 78, 14, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Prent', 'M', 27, 47, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Darren', 'H', 82, 31, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jessica', 'H', 21, 46, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Engelbert', 'H', 76, 30, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sorcha', 'M', 71, 42, 8);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Barn', 'M', 87, 32, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rick', 'M', 90, 15, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Daffie', 'H', 17, 48, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Meta', 'M', 87, 15, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Elise', 'M', 13, 6, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Brynne', 'H', 89, 14, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Charissa', 'H', 100, 13, 18);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Davide', 'H', 51, 8, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Amalie', 'M', 81, 33, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rodd', 'M', 57, 3, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Honey', 'M', 2, 39, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Brook', 'M', 95, 13, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Micheline', 'M', 50, 30, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Albertina', 'H', 77, 49, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Alic', 'M', 16, 5, 8);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Chucho', 'H', 48, 46, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ripley', 'H', 31, 37, 8);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Leanora', 'M', 12, 42, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ricky', 'H', 47, 41, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sukey', 'H', 78, 2, 8);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Elsy', 'H', 94, 22, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Wendye', 'H', 70, 35, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Emmery', 'H', 5, 1, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Verine', 'M', 66, 40, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Alfy', 'H', 68, 49, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bryna', 'M', 52, 48, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Corrine', 'M', 77, 46, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Reuben', 'H', 82, 2, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Orelle', 'H', 48, 24, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Mayor', 'H', 12, 16, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Had', 'H', 85, 45, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Dena', 'H', 70, 23, 18);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jaymee', 'M', 35, 27, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ardith', 'H', 27, 2, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hughie', 'M', 16, 5, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Redd', 'M', 75, 16, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sidonia', 'M', 66, 8, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sheelagh', 'M', 50, 1, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rowe', 'M', 75, 21, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Aurelea', 'H', 79, 20, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sampson', 'H', 13, 25, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gery', 'H', 29, 4, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Mollie', 'H', 71, 49, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gypsy', 'M', 87, 44, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Corena', 'H', 5, 30, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Codie', 'H', 47, 27, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Kristan', 'H', 19, 37, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Scotty', 'M', 25, 46, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Vinni', 'M', 87, 32, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Pammy', 'M', 57, 9, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rubina', 'M', 2, 38, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Flinn', 'H', 84, 35, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Elizabeth', 'H', 99, 49, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Poppy', 'H', 25, 22, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Daisie', 'M', 7, 13, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jecho', 'M', 8, 45, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Elicia', 'M', 100, 2, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Alfonso', 'M', 30, 49, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Kora', 'H', 61, 18, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Dyan', 'M', 8, 2, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Adria', 'M', 43, 33, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Abbot', 'H', 2, 48, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Arri', 'M', 34, 18, 8);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ivette', 'H', 80, 20, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rand', 'H', 87, 12, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Herbert', 'M', 10, 5, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Homer', 'M', 68, 22, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Graeme', 'H', 6, 35, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bealle', 'H', 82, 22, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gisele', 'H', 62, 3, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Miriam', 'M', 65, 48, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Logan', 'H', 93, 18, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Edita', 'H', 33, 3, 8);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Allard', 'H', 11, 47, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sharai', 'H', 13, 20, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sawyer', 'H', 58, 42, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jerome', 'H', 37, 29, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rivkah', 'M', 58, 7, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Marven', 'M', 14, 30, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Claude', 'H', 12, 9, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sayre', 'H', 2, 1, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bettina', 'M', 68, 12, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Henry', 'M', 77, 27, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Elonore', 'H', 37, 34, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Morgen', 'M', 25, 7, 2);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Willem', 'M', 16, 9, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Beatrisa', 'H', 35, 42, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Fulton', 'H', 10, 44, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Saunder', 'M', 8, 29, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bren', 'M', 17, 13, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Theresa', 'H', 24, 22, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Victoir', 'H', 94, 7, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Matilde', 'H', 93, 24, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Pru', 'H', 94, 39, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Consuela', 'M', 58, 44, 6);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Jock', 'H', 15, 25, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Chelsey', 'H', 56, 44, 6);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Dorthy', 'M', 42, 11, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Nanni', 'H', 18, 5, 6);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sophronia', 'M', 27, 27, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ritchie', 'M', 54, 31, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hedvig', 'H', 68, 22, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rowan', 'H', 19, 19, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Robbie', 'H', 100, 29, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Adora', 'M', 74, 27, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Sidney', 'M', 7, 28, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Christian', 'M', 96, 18, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Brucie', 'M', 63, 35, 16);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Nikki', 'H', 93, 10, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Vale', 'H', 71, 33, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Bendite', 'H', 44, 19, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Calley', 'H', 92, 48, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hailey', 'M', 33, 22, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Juliana', 'H', 77, 5, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Emmit', 'H', 43, 24, 1);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ricki', 'M', 58, 25, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Timothea', 'M', 79, 22, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Morry', 'M', 44, 26, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Owen', 'M', 68, 11, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Rebekkah', 'H', 47, 44, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Mabel', 'H', 3, 48, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gelya', 'M', 17, 47, 18);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Katuscha', 'M', 33, 28, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Lila', 'M', 77, 46, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Stace', 'H', 83, 24, 18);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Elspeth', 'M', 95, 36, 13);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Arthur', 'H', 17, 36, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Conny', 'H', 19, 36, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Karyl', 'M', 73, 10, 21);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ettore', 'H', 17, 41, 9);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gaston', 'H', 98, 31, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Kingsly', 'M', 48, 49, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Irena', 'M', 25, 23, 3);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Xylina', 'M', 16, 9, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Washington', 'H', 90, 27, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Karilynn', 'H', 70, 9, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Selig', 'H', 71, 23, 20);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Zabrina', 'M', 83, 18, 12);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Matthias', 'H', 84, 33, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Meagan', 'H', 56, 40, 22);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Merrill', 'M', 1, 32, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Morganica', 'M', 72, 8, 6);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Benedikta', 'M', 57, 27, 15);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Lenette', 'H', 79, 29, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Borden', 'M', 19, 18, 10);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Claudius', 'M', 66, 32, 25);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Graehme', 'M', 5, 11, 14);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Tammie', 'H', 22, 28, 11);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Giacinta', 'M', 94, 8, 7);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Hadria', 'M', 31, 27, 19);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Mathilde', 'H', 64, 49, 17);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Julissa', 'M', 48, 26, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Ros', 'H', 38, 5, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Harlan', 'H', 17, 24, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Guillema', 'H', 87, 11, 24);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Isacco', 'H', 72, 6, 4);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Gradey', 'M', 32, 24, 23);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Veronica', 'M', 58, 9, 5);
insert into animales (nombre, sexo, edad, id_especie, id_habitat) values ('Almeda', 'H', 55, 40, 4);
